# float64 DEFAULT_TIMEOUT = 1.0
# float64 DEFAULT_TIMEVAL = 3.0
# server: TMSVR, TMSCT
# connect/reconnect: Connection phase.
# connect == true. Keep connection alive if enabled.
# reconnect == true. Attempt to reconnect if the connection fails.

int8 TMSVR = 0
int8 TMSCT = 1

int8 server
bool connect
bool reconnect
float64 timeout
float64 timeval
---
# ok: Connection status
bool ok
